/**
 * Agent Types - Core type definitions for Cyne Multi-Agent System
 * 
 * This module defines the foundational types for the multi-agent architecture
 * that powers Cyne's advanced code analysis and generation capabilities.
 */

import { Tool } from '../Tool'
import { UUID } from 'crypto'

// ============================================================================
// Agent Core Types
// ============================================================================

/**
 * Agent capability categories - what an agent specializes in
 */
export type AgentCapability =
  | 'code_analysis'
  | 'architecture'
  | 'security'
  | 'performance'
  | 'documentation'
  | 'refactoring'
  | 'testing'
  | 'debugging'
  | 'code_generation'
  | 'review'

/**
 * Agent status during task execution
 */
export type AgentStatus =
  | 'idle'
  | 'initializing'
  | 'analyzing'
  | 'processing'
  | 'waiting'
  | 'complete'
  | 'error'

/**
 * Priority levels for task execution
 */
export type Priority = 'critical' | 'high' | 'medium' | 'low'

/**
 * Core agent definition
 */
export interface Agent {
  id: string
  name: string
  description: string
  capabilities: AgentCapability[]
  systemPrompt: string
  tools: Tool[]
  maxConcurrentTasks?: number
  defaultPriority?: Priority
}

/**
 * Agent instance during runtime
 */
export interface AgentInstance {
  agent: Agent
  status: AgentStatus
  currentTask?: AgentTask
  startTime?: number
  metrics: AgentMetrics
}

/**
 * Metrics tracked per agent
 */
export interface AgentMetrics {
  tasksCompleted: number
  totalTokensUsed: number
  averageResponseTime: number
  errorCount: number
}

// ============================================================================
// Task Types
// ============================================================================

/**
 * Task status during execution
 */
export type TaskStatus =
  | 'pending'
  | 'queued'
  | 'running'
  | 'paused'
  | 'complete'
  | 'error'
  | 'cancelled'

/**
 * A task assigned to an agent
 */
export interface AgentTask {
  id: UUID
  agentId: string
  input: string
  context?: TaskContext
  status: TaskStatus
  progress: number // 0-100
  priority: Priority
  dependencies?: UUID[] // Task IDs this depends on
  result?: AgentResult
  error?: AgentError
  createdAt: number
  startedAt?: number
  completedAt?: number
}

/**
 * Context provided to a task
 */
export interface TaskContext {
  projectRoot?: string
  activeFiles?: string[]
  recentChanges?: string[]
  userPreferences?: Record<string, unknown>
  parentTaskId?: UUID
  sharedMemory?: Map<string, unknown>
}

/**
 * Result from an agent task
 */
export interface AgentResult {
  success: boolean
  output: string
  findings?: Finding[]
  recommendations?: Recommendation[]
  artifacts?: Artifact[]
  metrics?: TaskMetrics
}

/**
 * Error from agent execution
 */
export interface AgentError {
  code: string
  message: string
  recoverable: boolean
  suggestion?: string
}

/**
 * Metrics for a completed task
 */
export interface TaskMetrics {
  durationMs: number
  tokensUsed: number
  toolCalls: number
  retries: number
}

// ============================================================================
// Finding & Recommendation Types
// ============================================================================

/**
 * Severity levels for findings
 */
export type Severity = 'critical' | 'high' | 'medium' | 'low' | 'info'

/**
 * A finding from agent analysis
 */
export interface Finding {
  id: string
  type: string
  severity: Severity
  title: string
  description: string
  location?: CodeLocation
  evidence?: string
  relatedFindings?: string[]
}

/**
 * Location in code
 */
export interface CodeLocation {
  file: string
  startLine: number
  endLine: number
  startColumn?: number
  endColumn?: number
}

/**
 * A recommendation from an agent
 */
export interface Recommendation {
  id: string
  title: string
  description: string
  priority: Priority
  effort: 'low' | 'medium' | 'high'
  impact: 'low' | 'medium' | 'high'
  relatedFindings?: string[]
  implementation?: string
  codeExample?: string
}

/**
 * Artifact generated by an agent
 */
export interface Artifact {
  id: string
  type: 'code' | 'documentation' | 'config' | 'report' | 'diagram'
  name: string
  content: string
  path?: string
}

// ============================================================================
// Orchestration Types
// ============================================================================

/**
 * Execution strategy for multi-prompt orchestration
 */
export type ExecutionStrategy = 'parallel' | 'sequential' | 'hybrid' | 'adaptive'

/**
 * How to aggregate results from multiple agents
 */
export type AggregationMethod = 'merge' | 'vote' | 'first' | 'weighted' | 'consensus'

/**
 * A prompt task in the orchestration pipeline
 */
export interface PromptTask {
  id: UUID
  prompt: string
  priority: Priority
  dependencies?: UUID[]
  targetAgent?: string
  timeout?: number
  retryPolicy?: RetryPolicy
}

/**
 * Retry configuration for failed tasks
 */
export interface RetryPolicy {
  maxRetries: number
  backoffMs: number
  backoffMultiplier: number
}

/**
 * Orchestration plan for executing multiple prompts
 */
export interface OrchestrationPlan {
  id: UUID
  tasks: PromptTask[]
  executionStrategy: ExecutionStrategy
  aggregationMethod: AggregationMethod
  timeout?: number
  checkpoints: Checkpoint[]
}

/**
 * Checkpoint for resumable execution
 */
export interface Checkpoint {
  id: UUID
  taskId: UUID
  state: unknown
  createdAt: number
}

// ============================================================================
// Coordination Types
// ============================================================================

/**
 * Message between agents
 */
export interface AgentMessage {
  id: UUID
  fromAgent: string
  toAgent: string | 'broadcast'
  type: 'request' | 'response' | 'notification' | 'query'
  content: unknown
  timestamp: number
  correlationId?: UUID
}

/**
 * Consensus result from multiple agents
 */
export interface ConsensusResult {
  agreementLevel: 'unanimous' | 'majority' | 'plurality' | 'none'
  agreementScore: number // 0-1
  mergedRecommendations: Recommendation[]
  conflicts: Conflict[]
  votingRecord: VotingRecord[]
}

/**
 * A conflict between agent recommendations
 */
export interface Conflict {
  id: string
  type: 'contradiction' | 'incompatible' | 'priority'
  agents: string[]
  description: string
  recommendations: Recommendation[]
  resolution?: Recommendation
}

/**
 * Record of agent voting
 */
export interface VotingRecord {
  agentId: string
  recommendationId: string
  vote: 'approve' | 'reject' | 'abstain'
  confidence: number
  reasoning?: string
}

// ============================================================================
// Event Types
// ============================================================================

/**
 * Events emitted during orchestration
 */
export type OrchestrationEvent =
  | { type: 'plan_created'; plan: OrchestrationPlan }
  | { type: 'task_started'; task: AgentTask }
  | { type: 'task_progress'; taskId: UUID; progress: number; message?: string }
  | { type: 'task_complete'; task: AgentTask; result: AgentResult }
  | { type: 'task_error'; task: AgentTask; error: AgentError }
  | { type: 'agent_message'; message: AgentMessage }
  | { type: 'consensus_reached'; result: ConsensusResult }
  | { type: 'checkpoint_created'; checkpoint: Checkpoint }
  | { type: 'plan_complete'; results: AgentResult[] }

/**
 * Listener for orchestration events
 */
export type OrchestrationEventListener = (event: OrchestrationEvent) => void
